export const fallbackCatalog = {
  brand: {
    name: 'ЧамБу',
    subtitle: 'Блины, завтраки и напитки в Грозном',
    description: 'Теплое меню для быстрых завтраков, спокойных встреч и сладких пауз.',
    phone: '+7 938 994-88-00',
    address: 'Грозный, ул. Хамзата Орзамиева, 30/30А',
    hours: 'Ежедневно 08:00-22:00',
    highlights: ['с собой', 'завтраки весь день', 'свежая выпечка'],
  },
  categories: [
    { id: 'pancakes', name: 'Блины', description: 'Сладкие и сытные блины.' },
    { id: 'breakfast', name: 'Завтраки', description: 'Сытное начало дня.' },
    { id: 'drinks', name: 'Напитки', description: 'Кофе, чай и лимонады.' },
  ],
  items: [
    {
      id: 'pancake-honey',
      categoryId: 'pancakes',
      name: 'Блин с медом',
      description: 'Тонкий румяный блин со сливочным маслом и горным медом.',
      price: 190,
      weight: '180 г',
      badges: ['нежный'],
      image: 'pancake-folded',
      imageUrl: '',
      available: true,
    },
    {
      id: 'pancake-chicken',
      categoryId: 'pancakes',
      name: 'Блин с курицей',
      description: 'Сытная начинка из курицы, сыра и зелени.',
      price: 290,
      weight: '240 г',
      badges: ['сытно'],
      image: 'pancake-stack',
      imageUrl: '',
      available: true,
    },
    {
      id: 'syrniki',
      categoryId: 'breakfast',
      name: 'Сырники',
      description: 'Творожные сырники со сметаной и ягодным соусом.',
      price: 340,
      weight: '240 г',
      badges: ['сладкое'],
      image: 'pancake-berries',
      imageUrl: '',
      available: true,
    },
    {
      id: 'pancake-berry',
      categoryId: 'pancakes',
      name: 'Блин с ягодами',
      description: 'Творожный крем, ягодный соус и легкая сахарная пудра.',
      price: 270,
      weight: '220 г',
      badges: ['хит'],
      image: 'pancake-berries',
      imageUrl: '',
      available: true,
    },
    {
      id: 'omelet-cheese',
      categoryId: 'breakfast',
      name: 'Омлет с сыром',
      description: 'Воздушный омлет, свежая зелень и теплый хлеб.',
      price: 320,
      weight: '260 г',
      badges: ['завтрак'],
      image: 'breakfast',
      imageUrl: '',
      available: true,
    },
    {
      id: 'croissant-salmon',
      categoryId: 'breakfast',
      name: 'Круассан с лососем',
      description: 'Хрустящий круассан, сливочный сыр, лосось и свежий огурец.',
      price: 430,
      weight: '210 г',
      badges: ['премиум'],
      image: 'croissant',
      imageUrl: '',
      available: true,
    },
    {
      id: 'raf-cardamom',
      categoryId: 'drinks',
      name: 'Раф кардамон',
      description: 'Сливочный кофе с тонкой пряной нотой.',
      price: 260,
      weight: '300 мл',
      badges: ['хит'],
      image: 'citrus',
      imageUrl: '',
      available: true,
    },
    {
      id: 'mountain-tea',
      categoryId: 'drinks',
      name: 'Горный чай',
      description: 'Душистый травяной сбор с медовым послевкусием.',
      price: 220,
      weight: '450 мл',
      badges: ['без кофеина'],
      image: 'tea',
      imageUrl: '',
      available: true,
    },
    {
      id: 'berry-lemonade',
      categoryId: 'drinks',
      name: 'Ягодный лимонад',
      description: 'Смородина, мята, цитрус и много льда.',
      price: 280,
      weight: '400 мл',
      badges: ['холодный'],
      image: 'lemonade',
      imageUrl: '',
      available: true,
    },
  ],
};
